### ISSUE TITLE
Bottom padding off

### ISSUE THREAD

**Issue by KoB-Kirito** [jakobbouchard/godot-filesystem-drawer#1]
Hey, I have godot set to 125% zoom, I think that interferes with the padding of the bottom?
![240509_1920_Godot_v4 3-dev6_win64](https://github.com/jakobbouchard/godot-filesystem-drawer/assets/51691757/c463f680-7776-4c6c-b73b-5585ccd59b05)
![240509_1920_Godot_v4 3-dev6_win64b](https://github.com/jakobbouchard/godot-filesystem-drawer/assets/51691757/0c74432a-4a97-4de8-8081-2ede0c1a8466)

**Comment by axeldeau** [comment]
```gdscript
...
var _bottom_offset: int = 200 #chose a number that looks good on your resolution
...
        # line 46
	_filesystem.get_child(3).get_child(0).size.y = size.y - _bottom_offset
	_filesystem.get_child(3).get_child(1).size.y = size.y - _bottom_offset
...
```

**Comment by KoB-Kirito** [comment]
Doesn't work if you work with multiple people on a project.
You should detect the resolution and scale.

**Comment by imjuniper** [comment]
Oh, thanks! I'll try looking into it tonight:)

**Comment by imjuniper** [comment]
I just pushed an update which should fix the issue! It will be up on the asset library soon-ish.

**Comment by KoB-Kirito** [comment]
Works like a charm, thank you <3
