### ISSUE TITLE
Godot crashes when I click "Show in FileSystem"

### ISSUE THREAD

**Issue by Driannn** [jakobbouchard/godot-filesystem-drawer#2]
On the script tap, Godot crashes when I click "Show file on Explorer"

![image](https://github.com/jakobbouchard/godot-filesystem-drawer/assets/77841664/8821575d-95fb-4ce3-ba32-125803d69973)

**Comment by imjuniper** [comment]
Hmmm, I might need to make a PR to Godot for this to not crash.

When you click on "Show in FileSystem" it calls the following function:

https://github.com/godotengine/godot/blob/bdc0316217940a8ccc80ce536547d42e6477adf4/editor/filesystem_dock.cpp#L770-L776

I'm pretty sure that it crashes when trying to focus the dock, but I can't confirm right now, I'd need to build the engine from source. I'll try to do so when I have time!

**Comment by imjuniper** [comment]
After a bit of research, this won't be super useful after 4.3 releases, so I won't do a PR in Godot and will probably retire the plugin after 4.3 releases.

See the following PR:
https://github.com/godotengine/godot/pull/86765

**Comment by Driannn** [comment]
Thank you for your work :)
